# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDemo' do
  use_frameworks!

  pod 'SnapKit', '~> 5.0.1'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MJRefresh', '~> 3.4.3'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'HandyJSON', '~> 5.0.0'
  pod 'Alamofire', '~> 5.4.0'
  
end
